### ISSUE TITLE
Defining multiple dataSources in config hash fails

### ISSUE THREAD

**Issue by jkleinlercher** [WASdev/ci.chef.wlp#36]
Hi,

when I define a serverconfig hash as follows, it creates a server.xml with only the dataSource db2, because dataSource db2 overwrites the db1 entry. This is how a hash normally works, but in the server.xml it is the normal way how you configure two different dataSources. So it seems with the current cookbook you cannot configure two different datasources. I read something about the compare_by_identity method of the Hash object, but I still didn't manage to get it right. Any ideas?

default[:wlp][:servers][:defaultServer] = {
"enabled" => true,
"serverName" => "defaultServer",
"description" => "Default Server",
"featureManager" => {
"feature" => [ "jsp-2.2" ]
},
"httpEndpoint" => {
"id" => "defaultHttpEndpoint",
"host" => "*",
"httpPort" => "9080",
"httpsPort" => "9443"
},
"dataSource" => {
"id" => "db1",
"jndiName" => "jdbc/db1"
},
"dataSource" => {
"id" => "db2",
"jndiName" => "jdbc/db2"
}
}

**Comment by benjamin-confino** [comment]
Hello. 

The syntax you're looking for is: 

"dataSource" => [{
"id" => "db1",
"jndiName" => "jdbc/db1"
}, {
"id" => "db2",
"jndiName" => "jdbc/db2"
}]

Anytime you create an array in the config hash it will create 
<arrayName> ...array element 1...</arrayName>
<arrayName> ...array element 2...</arrayName>

And if the array element is a hash it handles it correctly. 

Regards, 
Benjamin Confino

**Comment by jkleinlercher** [comment]
Oh great! That solved my problem! Thanks!
